---
- name: Install Tableau Server
  import_tasks: tableau_install.yml

- name: Register Tableau Server
  import_tasks: register_tableau.yml

- name: Configure Initial Node
  import_tasks: configure_initial.yml

- name: Add an Administrator Account
  import_tasks: add_admin.yml

- name: Configure SSL
  import_tasks: configure_ssl.yml

- name: Generate bootstrap
  import_tasks: generate_bootstrap.yml
