- name: Add a process to the additional nodes
  command: "{{ tsm_executable }} topology set-process -n node{{ item }} -pr clustercontroller -c 1 --username {{ tableau_user }} --password {{ tableau_server.tsm_password }}"
  with_sequence: start=1 end={{ groups['tableau-cluster-additional'] | length+1 }}
  tags: ["add_cluster_process"]

- name: Apply pending changes
  command: "{{ tsm_executable }} pending-changes apply --username {{ tableau_user }} --password {{ tableau_server.tsm_password }} --ignore-prompt --ignore-warnings"
  tags: [ "add_cluster_process", "apply-changes" ]
