---

- name: Install a tableau package from the internet.
  apt:
    deb: "{{ tableau_download_deb_url }}"
    update_cache: yes
  tags: ["install-additional"]

- name: Find script directory
  shell: "ls /opt/tableau/tableau_server/packages/ | grep script"
  register: tsm
  tags: ["install-additional"]

- name: Initialize TSM
  command: "/opt/tableau/tableau_server/packages/{{ tsm.stdout }}/initialize-tsm -b /home/ubuntu/bootstrap.json -u ubuntu --password {{ tableau_server.tsm_password }} --accepteula"
  become: yes
  ignore_errors: True
  tags: ["install-additional", "initialize-additional-tsm"]
